wiiu-pkg-config: fail if host pkg-config missing

diff --git a/pkg-config/pkg-config.in b/pkg-config/pkg-config.in
--- a/pkg-config/pkg-config.in
+++ b/pkg-config/pkg-config.in
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+command -v pkg-config >/dev/null 2>&1 || { echo >&2 "I require pkg-config but it's not installed.  Aborting."; exit 1; }
+
 # reset pkg-config variables to ensure we're not polluted by host libraries
 
 export PKG_CONFIG_DIR=
@@ -8,5 +10,6 @@ export PKG_CONFIG_SYSROOT_DIR=
 
 export PKG_CONFIG_LIBDIR=${DEVKITPRO}/portlibs/wiiu/lib/pkgconfig:${DEVKITPRO}/portlibs/ppc/lib/pkgconfig
 
+[[ "$1" == '--version' ]] && exec pkg-config --version
 exec pkg-config --static "$@"
 
